spec:

  templates:

  - name: train-and-predict
    parent: generic-task

    inputs:

      parameters:
      - name: docker-image
        value: z-ml
      - name: docker-tag
        value: latest

      - name: command
        value: python3 main.py

      artifacts:
      - name: data
        path: /app/data.json
      - name: main-script
        path: /app/main.py
        raw:
          data: |
            from modular.utils import save_json 
            from modular.utils import read_json
            from modular.functions import return_model
            from modular.functions import train_model
            from modular.functions import predict
            
            data = read_json('data.json')
            features = data["features"]
            labels = data["labels"]
            
            model = return_model()
            train_model(model, features, labels)

            predictions = predict(model, features)

            result = {}
            result["predictions"] = predictions

            save_json(result, 'result.json')

  
    outputs:
      artifacts:
      - name: predictions
        path: /app/predictions.json